<a href="https://colab.research.google.com/github/Gilles00/30-Days-of-Python/blob/master/Mathematics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [5]:
# vectors
v = np.array([5,-2,4])
v

array([ 5, -2,  4])

In [4]:
# matrices
m = np.array([[5,12],[-3,0]])
m

array([[ 5, 12],
       [-3,  0]])

In [6]:
# Row Vector
v.reshape(1,3)

array([[ 5, -2,  4]])

In [7]:
# Tensor is a collection of matrices
m1 = np.array([[5,12,6],[-3,0,14]])
m2 = np.array([[9,8,7],[1,3,-5]])
t = np.array([m1,m2])
t

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

In [8]:
# Adding Vectors
v1 = np.array([1,2,3,4,5])
v2 = np.array([5,4,3,2,1])
v1 + v2

array([6, 6, 6, 6, 6])

In [10]:
# Adding Vectors with a scalar
v1 + 1

array([2, 3, 4, 5, 6])